FC = gfortran
FFLAGS = -march=native -mtune=native -O3
FDEBUGFLAGS = -g -fbacktrace -ffpe-trap=zero,overflow,underflow,denormal
IDIR = -I/usr/local/include/fgsl/
LIBS = -lgsl -lfgsl -lopenblas -lm

all: cubicspline.exe

cubicspline.exe: interpolar.f90 direct_resolution_methods.o cubicspline.o
	$(FC) $(FFLAGS) -o $@ $(IDIR) $^ $(LIBS)

%.o: %.f90
	$(FC) -c $(FFLAGS) -o $@ $(IDIR) $<

debug: interpolar_fgsl.f90 direct_resolution_methods.f90 cubicspline.f90
	$(FC) -g $(FDEBUGFLAGS) -o cubicspline.exe $(IDIR) $^ $(LIBS)

clean:
	rm -f *.o *.mod *.exe